@DemoApi_HostAddress = https://localhost:7254

GET {{DemoApi_HostAddress}}/tasks
Accept: application/json

###

POST {{DemoApi_HostAddress}}/tasks
Content-Type: application/json

{
  "title": "My first task",
  "isCompleted": false
}
